### PR TITLE
bugfix: Tape2007 checkerboard legacy model 

### PR DESCRIPTION
**Pull request by bch0w**
In PR #1150 I updated the legacy Checkerboard model for the Tape2007 example so that the model read in by `xspecfem2D` was correctly defined as a smooth checkerboard model. However upon further inspection I realized I did not adjust the labelled coordinate system of the actual `model_velocity.dat_checker` file (i.e., columns 1 and 2 in the file).

The consequence is that although the example runs fine since it doesn't take coordinate information from the `model_velocity.dat_checker` file, any User who attempted to plot the `model_velocity.dat_checker` file directly (e.g., using Python), will have been met with a jumbled mess. This PR updates the `model_velocity.dat_checker` file so that its internal coordinates correctly define a smooth checkerboard, while still conforming to the internally assumed coordinate system of `xspecfem2D`.

Heres a Python code snippet to plot the file, and the resulting figure. I also checked and confirmed that the model read in and used by `xspecfem2D` is the same.
```python
import numpy as np
import matplotlib.pyplot as plt
x, z, vp, vs = np.genfromtxt("model_velocity.dat_checker", dtype=float, usecols=[1,2,4,5]).T
plt.tricontourf(x, z, vp,  levels=250, cmap="seismic")
plt.show()
```
model_velocity dat_checker

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by danielpeter** [comment]
accept

On 15 Sep 2022, at 3:41 AM, buildbot-princeton ***@***.******@***.***>> wrote:



The files changed require a buildbot test. Buildbot has started.

**Comment by bch0w** [comment]
Hi Daniel, it seems like Buildbot closed this PR instead of merging it, but did not give any reason why. Please let me know if I need to change anything to my commits or forked repo to get this merged.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
There was an error running buildbot. The system administrator needs to look into it

**Pull request merged**
