### PR TITLE
fixed the CIG logo

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by komatits** [comment]
accept

On 01/21/2015 03:12 AM, buildbot-princeton wrote:
> The files changed do not require a buildbot test. The maintainers can
> commit these changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/187#issuecomment-70772982>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
BuildBot apparently missed the "accept", thus merged manually.

**Comment by luet** [comment]
I have identified the problem. It has to do with multiple PRs going on at
the same time. I think the fix should be easy. The problem is that all the
processes were writing to the same file. I am working on it now. Meanwhile
you can keep committing as usual.

On Tue, Jan 20, 2015 at 9:30 PM, Dimitri Komatitsch <
notifications@github.com> wrote:

> BuildBot apparently missed the "accept", thus merged manually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/187#issuecomment-70774455>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by luet** [comment]
This problem should be fixed now. Buildbot can handle multiple PRs opened at the same time.

**Comment by komatits** [comment]
Thanks!

On 01/21/2015 10:24 PM, David Luet wrote:
> This problem should be fixed now. Buildbot can handle multiple PRs
> opened at the same time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/187#issuecomment-70924540>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
