### PR TITLE
fixed broken examples

### PR DESCRIPTION
**Pull request by rmodrak**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by rmodrak** [comment]
Hi all,

I tried fixing the broken examples.  If you notice any remaining problems, please let me know.

While I was at, it cleaned up a bit by moving three very lengthy parameters descriptions from the ``Par_file`` to the user manual.  For me, the result is a bit nicer (I hope others agree).

Thanks,
Ryan

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 148](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/148).

**Comment by komatits** [comment]
accept

On 03/25/2015 05:27 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 148
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/148>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/261#issuecomment-85828213>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
