### PR TITLE
updates configuration and simulation preparation

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 352](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/352). Fix your mistakes and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 353](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/353).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
