### PR TITLE
Etienne Bachmann fixed the write_seismograms() inverted buffer bug

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 99](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/99).

**Comment by komatits** [comment]
accept

On 01/13/2015 03:12 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 99
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/99>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/181#issuecomment-69749039>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
FYI, you can use `git commit --author=<author>` to attribute the commit to the correct author.

**Pull request merged**
