### PR TITLE
Remove NR routines

### LINKED ISSUE #13: remove copyrighted routines from attenuation_compute_param.c
This file appears to contain code from Numerical Recipes. NR code is not license compatible with open source code. It should be replaced.

### PR DESCRIPTION
**Pull request by QuLogic**
As noted in #13, these routines should be removed. They are unnecessary at this point since @komatits notes the new algorithm is working well.

Fixes #13.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 288](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/288).

**Comment by komatits** [comment]
reject

On 10/06/2015 02:54 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 288
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/288>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/430#issuecomment-145712368>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
We need to keep them for now, the new routines are not working well yet 
(at least not fully tested); I have canceled your pull request

On 10/06/2015 02:43 AM, Elliott Sales de Andrade wrote:
> As noted in #13 <https://github.com/geodynamics/specfem2d/issues/13>,
> these routines should be removed. They are unnecessary at this point
> since @komatits <https://github.com/komatits> notes the new algorithm is
> working well.
>
> Fixes #13 <https://github.com/geodynamics/specfem2d/issues/13>.
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/geodynamics/specfem2d/pull/430
>
>
>         Commit Summary
>
>   * Remove unnecessary NR routines.
>
>
>         File Changes
>
>   * *D* src/specfem2D/attenuation_compute_param.c
>     <https://github.com/geodynamics/specfem2d/pull/430/files#diff-0> (492)
>   * *M* src/specfem2D/attenuation_model.f90
>     <https://github.com/geodynamics/specfem2d/pull/430/files#diff-1> (117)
>   * *M* src/specfem2D/compute_forces_viscoelastic.F90
>     <https://github.com/geodynamics/specfem2d/pull/430/files#diff-2> (21)
>   * *M* src/specfem2D/rules.mk
>     <https://github.com/geodynamics/specfem2d/pull/430/files#diff-3> (1)
>
>
>         Patch Links:
>
>   * https://github.com/geodynamics/specfem2d/pull/430.patch
>   * https://github.com/geodynamics/specfem2d/pull/430.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/430>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
That's unfortunate; I'd like to get rid of NR...

**Comment by komatits** [comment]
I agree. That is planned for next summer. I already got rid of all NR 
routines in all other parts of the code (erfc() function for the 
earthquake source and so on).

On 10/07/2015 01:28 AM, Elliott Sales de Andrade wrote:
> That's unfortunate; I'd like to get rid of NR...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/430#issuecomment-146032991>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
