### PR TITLE
updates simple_topography_and_also_a_simple_fluid_layer/ example; updates reading of Par_files

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 428](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/428). Fix your mistakes and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 429](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/429). Fix your mistakes and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
I changed the reference seismograms, reran the test and just merged.

**Pull request merged**
