### PR TITLE
updates parameter names in Par_file

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 783](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/783). Please fix the problems and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 784](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/784). Please fix the problems and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by danielpeter** [comment]
accept

On 18 Nov 2021, at 6:10 PM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 785<https://urldefense.com/v3/__http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/785__;!!Nmw4Hv0!hv2TobJ47RbAh6N7luZQ19_KlNnRsyAatUMpVc2IHJCAYQFBMHSF4YO5JHKDK4iCF7EFqA$>.

**Pull request merged**
