### PR TITLE
Two small changes

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Your changes are not mergeable. Please fix the problem and open a new pull-request

**Comment by komatits** [comment]
Let me know if this is a BuildBot problem or a problem with the pull 
request (since the message below gives no details). I can merge it 
manually if needed.

Dimitri.

On 12/17/2015 11:04 AM, buildbot-princeton wrote:
> Your changes are not mergeable. Please fix the problem and open a new
> pull-request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/511#issuecomment-165405849>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKT2xerjesETK2fLEQYTuiens6b2Pks5pQoA7gaJpZM4G3ObJ.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
It's problem with the commit. From a fresh clone on the devel branch:

    $ git pull --ff-only git@github.com:bottero/specfem2d devel
    remote: Counting objects: 18, done.
    remote: Compressing objects: 100% (13/13), done.
    remote: Total 18 (delta 7), reused 4 (delta 4), pack-reused 1
    Unpacking objects: 100% (18/18), done.
   From github.com:bottero/specfem2d
     * branch            devel      -> FETCH_HEAD
    fatal: Not possible to fast-forward, aborting.

My guess is that since the commit that pulled the changes from the central repo (269246) are from November 12,  @bottero local repo is out of sync. Doing a `git pull`, resolving the potential conflicts  and opening a new PR should fix the problem.

David

**Comment by komatits** [comment]
Hi David,

Thanks!

Dimitri.

On 12/17/2015 03:26 PM, David Luet wrote:
> It's problem with the commit. From a fresh clone on the devel branch:
>
> |$ git pull --ff-only git@github.com:bottero/specfem2d devel remote:
> Counting objects: 18, done. remote: Compressing objects: 100% (13/13),
> done. remote: Total 18 (delta 7), reused 4 (delta 4), pack-reused 1
> Unpacking objects: 100% (18/18), done. |
>
>  From github.com:bottero/specfem2d
> * branch devel -> FETCH_HEAD
> fatal: Not possible to fast-forward, aborting.
>
> My guess is that since the commit that pulled the changes from the
> central repo (269246) are from November 12, @bottero
> <https://github.com/bottero> local repo is out of sync. Doing a |git
> pull|, resolving the potential conflicts and opening a new PR should fix
> the problem.
>
> David
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/511#issuecomment-165464859>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
