### PR TITLE
Add some modifications done with Eric Rosenkrantz (source options 8 and 9 used

### PR DESCRIPTION
**Pull request by bottero**
respectively to read source wavelet from a file and to send a burst)

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 259](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/259). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 260](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/260).

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Comment by komatits** [comment]
accept

On 09/10/2015 01:54 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 260
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/260>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/397#issuecomment-139212882>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKX1X2DRX20FAegYj2_njxEhZHcjmks5owWbigaJpZM4F658J.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
