### PR TITLE
Remove all SOURCE files in EXAMPLES

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 263](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/263). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 264](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/264). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
Are you able to run the `run_this_example.sh` script in 

    EXAMPLES/simple_topography_and_also_a_simple_fluid_layer

I just tried and after `./xmeshfem2D` I get:

    ...
     vs =    1343.37500000000     
    rho =    2200.00000000000     
    Poisson's ratio =   0.202726178174505     
    QKappa =    9999.00000000000     
    Qmu =    9999.00000000000     
     -----
     
    Parameter file successfully read... 
    total number of non blank and non comment lines in SOURCE file should be a multiple of NLINES_PER_SOURCE

I am not sure whether it's an error or warning, but I run specfem, it exits with an error:

    $ ./xspecfem2D 
      error opening file OUTPUT/Database***
      Error detected, aborting MPI... proc 
      error, program ended in exit_MPI

Have you tried running this example?

Thanks,
David

**Comment by bottero** [comment]
Yes for me run_this_example.sh works! I have changed the source file
(SOURCE_simple_topo)... I am trying to commit it (with the other ones) but
my commit is rejected.

Thanks

Alexis

2015-09-15 17:42 GMT+02:00 David Luet <notifications@github.com>:

**Comment by komatits** [comment]
Did you commit your change for the value of NLINES_PER_SOURCE?
(in setup/constants.h.in, not only in setup.constants.h)

Thanks,
Dimitri.

On 09/15/2015 05:57 PM, Bottero wrote:
> Yes for me run_this_example.sh works! I have changed the source file
> (SOURCE_simple_topo)... I am trying to commit it (with the other ones) but
> my commit is rejected.
>
> Thanks
>
> Alexis
>
> 2015-09-15 17:42 GMT+02:00 David Luet <notifications@github.com>:
>
>  > Are you able to run the run_this_example.sh script in
>  >
>  > EXAMPLES/simple_topography_and_also_a_simple_fluid_layer
>  >
>  > I just tried and after ./xmeshfem2D I get:
>  >
>  > ...
>  > vs = 1343.37500000000
>  > rho = 2200.00000000000
>  > Poisson's ratio = 0.202726178174505
>  > QKappa = 9999.00000000000
>  > Qmu = 9999.00000000000
>  > -----
>  >
>  > Parameter file successfully read...
>  > total number of non blank and non comment lines in SOURCE file should
> be a multiple of NLINES_PER_SOURCE
>  >
>  > I am not sure whether it's an error or warning, but I run specfem, it
>  > exits with an error:
>  >
>  > $ ./xspecfem2D
>  > error opening file OUTPUT/Database***
>  > Error detected, aborting MPI... proc
>  > error, program ended in exit_MPI
>  >
>  > Have you tried running this example?
>  >
>  > Thanks,
>  > David
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem2d/pull/403#issuecomment-140436664>
>  > .
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/403#issuecomment-140441593>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by EtienneBachmann** [comment]
I think so, the constants.h.in is updated in my fork. The strange point is that the former commit of Alexis passed the buildbot test, it shouldn t have. Now for instance my current commit also fail because of it. I wonder if any commit can fix this now, or if a manual operation should be done with the buildbot.

**Comment by komatits** [comment]
We can maybe manually accept all the pending pull requests on GitHub. 
Just let me know if you would like me to do that.

Thanks,
Dimitri.

On 09/15/2015 06:12 PM, EtienneBachmann wrote:
> I think so, the constants.h.in is updated in my fork. The strange point
> is that the former commit of Alexis passed the buildbot test, it shouldn
> t have. Now for instance my current commit also fail because of it. I
> wonder if any commit can fix this now, or if a manual operation should
> be done with the buildbot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/403#issuecomment-140447015>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
Let me look first. I'll get back to you.
David

On Tue, Sep 15, 2015 at 12:14 PM, Dimitri Komatitsch <
notifications@github.com> wrote:

>
> We can maybe manually accept all the pending pull requests on GitHub.
> Just let me know if you would like me to do that.
>
> Thanks,
> Dimitri.
>
> On 09/15/2015 06:12 PM, EtienneBachmann wrote:
> > I think so, the constants.h.in is updated in my fork. The strange point
> > is that the former commit of Alexis passed the buildbot test, it shouldn
> > t have. Now for instance my current commit also fail because of it. I
> > wonder if any commit can fix this now, or if a manual operation should
> > be done with the buildbot.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/geodynamics/specfem2d/pull/403#issuecomment-140447015>.
> >
>
> --
> Dimitri Komatitsch
> CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
> UPR 7051, Marseille, France http://komatitsch.free.fr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/403#issuecomment-140447792>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by EtienneBachmann** [comment]
It seems a good idea, as long as the constants.h.in is updated and all the source files are updated. 
On my side specfem2D works fine.
NB : I am not sure about the test that buildbot is processing, but in this case, a "make clean make all" is not enough, a ./configure is necessary. This might explain why the former commit of Alexis passed the buildbot test.

**Comment by luet** [comment]
Ok. There is one mistake on my side. Let me fix it and rerun the tests.

On Tue, Sep 15, 2015 at 12:19 PM, EtienneBachmann <notifications@github.com>
wrote:

> It seems a good idea, as long as the constants.h.in is updated and all
> the source files are updated.
> On my side specfem2D works fine.
> NB : I am not sure about the test that buildbot is processing, but in this
> case, a "make clean make all" is not enough, a ./configure is necessary.
> This might explain why the former commit of Alexis passed the buildbot test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/403#issuecomment-140449332>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Perfect, thanks!

Dimitri.

On 09/15/2015 06:16 PM, David Luet wrote:
> Let me look first. I'll get back to you.
> David
>
> On Tue, Sep 15, 2015 at 12:14 PM, Dimitri Komatitsch <
> notifications@github.com> wrote:
>
>  >
>  > We can maybe manually accept all the pending pull requests on GitHub.
>  > Just let me know if you would like me to do that.
>  >
>  > Thanks,
>  > Dimitri.
>  >
>  > On 09/15/2015 06:12 PM, EtienneBachmann wrote:
>  > > I think so, the constants.h.in is updated in my fork. The strange point
>  > > is that the former commit of Alexis passed the buildbot test, it
> shouldn
>  > > t have. Now for instance my current commit also fail because of it. I
>  > > wonder if any commit can fix this now, or if a manual operation should
>  > > be done with the buildbot.
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > > <
>  >
> https://github.com/geodynamics/specfem2d/pull/403#issuecomment-140447015>.
>  > >
>  >
>  > --
>  > Dimitri Komatitsch
>  > CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
>  > UPR 7051, Marseille, France http://komatitsch.free.fr
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem2d/pull/403#issuecomment-140447792>
>  > .
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/403#issuecomment-140448152>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKXWfPpu7l4NsCWA1H2gNfqOhlAbCks5oyDvBgaJpZM4F8_Wv.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
It was a problem with a script that was building in the wrong directory.
I tested those commits: [build 266](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/266).
And the commits have been merged into the devel branch.
David

**Pull request merged**
