### PR TITLE
Some commits to document AXISYM option

### PR DESCRIPTION
**Pull request by bottero**
It had to be made for a while... Now everything is commited! A new fully commented example is available (the one of the JASA paper) and the manual has been updated.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
utils/Visualization/plot.py
This message is a warning only as this will be fixed by the automatic run of the code beautifier
Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" utils/Visualization/plot.py
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT utils/Visualization/plot.py-o utils/Visualization/plot.py
Although you should be aware that some characters won't be converted properly.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
There was an error running buildbot. The system administrator needs to look into it

**Comment by bottero** [comment]
I don't understand what have failed... I have commited no source code!

**Comment by luet** [comment]
It was a problem on the buildbot server side. The changes passed the tests [465](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/465).
@komatits I have merged it automatically. You don't need to do it.

**Pull request merged**
