### PR TITLE
Some modification to enforce_zero_radial_displacements_on_the_axis

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 199](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/199). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
Let me take care of this one. I was just switching the scripts to using a
new MPI.
Give me about one hour. I'll rerun it and commit it.
Thanks,
David

On Thu, Apr 30, 2015 at 9:58 AM, buildbot-princeton <
notifications@github.com> wrote:

> Your changes failed the buildbot test. See build 199
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/199>.
> Fix your mistakes and push your changes back to your branch
> bottero/specfem2d:devel. This pull-request will be reopened automatically.
> You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/321#issuecomment-97803607>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by luet** [comment]
Actually, @bottero you have some unresolved conflicts.

src/specfem2D/axisymmetric_routines.f90:269.1:

    <<<<<<< HEAD
     1
    Error: Invalid character in name at (1)
    src/specfem2D/axisymmetric_routines.f90:272.1:
    
    =======
     1
    Error: Invalid character in name at (1)
    src/specfem2D/axisymmetric_routines.f90:273.23:
    
            do j = 1,NGLLZ ! For each depth
                       1
    src/specfem2D/axisymmetric_routines.f90:271.39:
    
            do j = 1,NGLLZ ! For each depth
                                       2
    Error: Variable 'j' at (1) cannot be redefined inside loop beginning at (2)
    src/specfem2D/axisymmetric_routines.f90:274.1:
    
    >>>>>>> 08f151d776f685550d25519cda04f72c0cd5bbc9


How about you fix these and wait for me to let you know when buildbot is back up.

**Comment by luet** [comment]
I am done upgrading the compilers. Buildbot is running.

**Comment by luet** [comment]
Also doing

    $ git status
and looking at the output, would catch the merging and conflict problem.

**Comment by komatits** [comment]
In that case you can use:

git mergetool --tool=meld

to resolve all the conflicts ("meld" is very useful for that).

Dimitri.

On 04/30/2015 04:04 PM, David Luet wrote:
> Actually, @bottero <https://github.com/bottero> you have some unresolved
> conflicts.
>
> src/specfem2D/axisymmetric_routines.f90:269.1:
>
> |<<<<<<< HEAD
>   1
> Error: Invalid character in name at (1)
> src/specfem2D/axisymmetric_routines.f90:272.1:
>
> =======
>   1
> Error: Invalid character in name at (1)
> src/specfem2D/axisymmetric_routines.f90:273.23:
>
>          do j = 1,NGLLZ ! For each depth
>                     1
> src/specfem2D/axisymmetric_routines.f90:271.39:
>
>          do j = 1,NGLLZ ! For each depth
>                                     2
> Error: Variable 'j' at (1) cannot be redefined inside loop beginning at (2)
> src/specfem2D/axisymmetric_routines.f90:274.1:
>
>>>>>>>> 08f151d776f685550d25519cda04f72c0cd5bbc9
> |
>
> How about you fix these and wait for me to let you know when buildbot is
> back up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/321#issuecomment-97806917>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by bottero** [comment]
Thank you! I have made an other commit.

Alexis

2015-04-30 17:41 GMT+02:00 Dimitri Komatitsch <notifications@github.com>:

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Comment by luet** [comment]
Can we just close this pull-request then?

On Mon, May 4, 2015 at 9:45 AM, buildbot-princeton <notifications@github.com
> wrote:

> You pushed to your local branch while your previous changes are waiting to
> be committed. We assume that you did not intend for these changes to be
> part of the currently opened pull-request and ignore those changes. If you
> want these changes to be committed, please open a new pull-request.
>
> *Note to maintainers:* when you accept the original pull-request, the
> message from buildbot will say that it *closed* the pull-request, as
> opposed to the usual message that it *merged* the pull-request. In spite
> of this, the initial pull-request will be merged after you accept it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/321#issuecomment-98707704>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by bottero** [comment]
Yes!

**Pull request closed without merging**
