### PR TITLE
integrate the add coupling with the poroelastic side into compute_coupling_acoustic_po.f90

### PR DESCRIPTION
**Pull request by xiezhinan**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by komatits** [comment]
accept

On 03/30/2015 10:01 AM, buildbot-princeton wrote:
> The files changed require a buildbot test. Buildbot has started.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/269#issuecomment-87583910>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 159](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/159).

**Comment by komatits** [comment]
accept

On 03/30/2015 10:10 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 159
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/159>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/269#issuecomment-87584944>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
