### PR TITLE
Added smoothing program for postprocessing

### PR DESCRIPTION
**Pull request by EtienneBachmann**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 272](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/272).

**Comment by QuLogic** [comment]
@luet Does the buildbot not build the postprocessing tools? I don't think this should have passed.

**Comment by komatits** [comment]
accept

On 09/16/2015 02:49 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 272
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/272>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/405#issuecomment-140589326>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
@QuLogic Let me look. It looks like it only tested the last commit out of the 3 that @EtienneBachmann submitted. The [patch](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/272/steps/git/logs/patch) does not contain all the changes.

**Comment by luet** [comment]
I understand why buildbot only tested the last patch of the commit. We have two sets of identical commits:
2d065694 and 6355a9ac: Add MPI support for xcombine_sum
6adcb505 and 9df4adbc:  Remove Stacey saving inside the timeloop

So the patch used by buildbot only includes the changes that hadn't been applied before.

**Comment by luet** [comment]
@QuLogic What do I need to do to build the post-processing tools?

**Comment by QuLogic** [comment]
Looks like it's not built by default, so I guess you need to do `make postprocess`.

**Comment by komatits** [comment]
Yes, I confirm what Elliott says, the commit that went through yesterday 
broke the code (in the "postprocess" part), which means BuildBot likely 
does not check them. (at least not without MPI, since "make postprocess" 
worked OK with MPI but failed without)

I am going to commit a temporary fix in a few minutes.

Dimitri.

On 09/16/2015 10:26 PM, Elliott Sales de Andrade wrote:
> Looks like it's not built by default, so I guess you need to do |make
> postprocess|.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/405#issuecomment-140878257>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
You could also just do "make all"


On 09/16/2015 10:26 PM, Elliott Sales de Andrade wrote:
> Looks like it's not built by default, so I guess you need to do |make
> postprocess|.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/405#issuecomment-140878257>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Done.

Dimitri.

On 09/17/2015 11:32 AM, Dimitri Komatitsch wrote:
>
> I am going to commit a temporary fix in a few minutes.
>
> Dimitri.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
("make all" is probably better for the future, if/when we add new 
modules or directories)

On 09/17/2015 12:10 PM, Dimitri Komatitsch wrote:
>
> You could also just do "make all"
>
>
> On 09/16/2015 10:26 PM, Elliott Sales de Andrade wrote:
>> Looks like it's not built by default, so I guess you need to do |make
>> postprocess|.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem2d/pull/405#issuecomment-140878257>.
>>
>>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
With every config options?

On Thu, Sep 17, 2015 at 6:10 AM, Dimitri Komatitsch <
notifications@github.com> wrote:

>
> You could also just do "make all"
>
>
> On 09/16/2015 10:26 PM, Elliott Sales de Andrade wrote:
> > Looks like it's not built by default, so I guess you need to do |make
> > postprocess|.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/geodynamics/specfem2d/pull/405#issuecomment-140878257>.
> >
>
> --
> Dimitri Komatitsch
> CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
> UPR 7051, Marseille, France http://komatitsch.free.fr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/405#issuecomment-141034822>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by luet** [comment]
I have implemented the compilation of the post-processing tools in
buildbot. The stepped are suffixed "_pp":

--with-mpi_make_pp
--with-mpi_config_pp
--without-mpi_make_pp
--without-mpi_config_pp
--enable-double-precision_make_pp
--enable-double-precision_config_pp
--disable-double-precision_make_pp
--disable-double-precision_config_pp

See build 277
<http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/277>
.

All the make steps are just:
$ make postprocess


On Thu, Sep 17, 2015 at 9:12 AM, David Luet <luet@princeton.edu> wrote:

> With every config options?
>
> On Thu, Sep 17, 2015 at 6:10 AM, Dimitri Komatitsch <
> notifications@github.com> wrote:
>
>>
>> You could also just do "make all"
>>
>>
>> On 09/16/2015 10:26 PM, Elliott Sales de Andrade wrote:
>> > Looks like it's not built by default, so I guess you need to do |make
>> > postprocess|.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/geodynamics/specfem2d/pull/405#issuecomment-140878257
>> >.
>> >
>>
>> --
>> Dimitri Komatitsch
>> CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
>> UPR 7051, Marseille, France http://komatitsch.free.fr
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem2d/pull/405#issuecomment-141034822>
>> .
>>
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Yes, that is usually what I do.

Dimitri.

On 09/17/2015 03:12 PM, David Luet wrote:
> With every config options?
>
> On Thu, Sep 17, 2015 at 6:10 AM, Dimitri Komatitsch <
> notifications@github.com> wrote:
>
>  >
>  > You could also just do "make all"
>  >
>  >
>  > On 09/16/2015 10:26 PM, Elliott Sales de Andrade wrote:
>  > > Looks like it's not built by default, so I guess you need to do |make
>  > > postprocess|.
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > > <
>  >
> https://github.com/geodynamics/specfem2d/pull/405#issuecomment-140878257>.
>  > >
>  >
>  > --
>  > Dimitri Komatitsch
>  > CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
>  > UPR 7051, Marseille, France http://komatitsch.free.fr
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem2d/pull/405#issuecomment-141034822>
>  > .
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/405#issuecomment-141078901>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKXjPSClmdizpJwcI-lxsShcvGlYkks5oyrO6gaJpZM4F-Dgu.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
