### PR TITLE
updated "configure" for the new name of the README file

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by QuLogic** [comment]
Oops, looks like we did the same thing!

**Comment by komatits** [comment]
Let me cancel mine then.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 234](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/234).

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 235](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/235). Fix your mistakes and push your changes back to your branch komatits/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by komatits** [comment]
accept

On 05/21/2015 09:44 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 234
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/234>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/359#issuecomment-104399694>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKQhtmBZaCJ42aV3hOB_aKVQbqnumks5oLi0IgaJpZM4Ej3Eg.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
No problem, change made by Elliott as well thus all set.

On 05/21/2015 09:44 PM, buildbot-princeton wrote:
> Your changes failed the buildbot test. See build 235
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/235>.
> Fix your mistakes and push your changes back to your branch
> komatits/specfem2d:devel. This pull-request will be reopened
> automatically. You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/359#issuecomment-104400059>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
