### PR TITLE
ran the beautifier (to which I added one new statement)

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 232](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/232). Fix your mistakes and push your changes back to your branch komatits/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
The problem was introduced in the previous commit: b8689253b
Even that one cannot be configured:

     ./configure FC=gfortran CC=gcc MPIFC=mpif90 MPICC=mpicc
--disable-double-precision
     configure: error: cannot find sources (README) in . or ..

The README was renamed to README.md in commit 1187ac507f. So I am guessing
that configure is looking for it. This is not a buildbot problem.

Thanks,
David

On Thu, May 21, 2015 at 1:12 PM, buildbot-princeton <
notifications@github.com> wrote:

> Your changes failed the buildbot test. See build 232
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/232>.
> Fix your mistakes and push your changes back to your branch
> komatits/specfem2d:devel. This pull-request will be reopened automatically.
> You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/357#issuecomment-104359492>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
Thanks! Fixed.

Dimitri.

On 05/21/2015 08:50 PM, David Luet wrote:
> The problem was introduced in the previous commit: b8689253b
> Even that one cannot be configured:
>
> ./configure FC=gfortran CC=gcc MPIFC=mpif90 MPICC=mpicc
> --disable-double-precision
> configure: error: cannot find sources (README) in . or ..
>
> The README was renamed to README.md in commit 1187ac507f. So I am guessing
> that configure is looking for it. This is not a buildbot problem.
>
> Thanks,
> David
>
> On Thu, May 21, 2015 at 1:12 PM, buildbot-princeton <
> notifications@github.com> wrote:
>
>  > Your changes failed the buildbot test. See build 232
>  >
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/232>.
>  > Fix your mistakes and push your changes back to your branch
>  > komatits/specfem2d:devel. This pull-request will be reopened
> automatically.
>  > You don't need to create a new pull request
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem2d/pull/357#issuecomment-104359492>
>  > .
>  >
>
>
>
> --
> David Luet
> Linux Administrator/Software & Programming Analyst
> Department of Geosciences & PICSciE
> Princeton University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/357#issuecomment-104385706>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
