### PR TITLE
updates tomo file interpolation (using floating-point comparisons w/ small numerical tolerance); adds comments

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 789](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/789).

**Comment by danielpeter** [comment]
accept

**Comment by danielpeter** [comment]
accept

On 12 Jul 2022, at 12:10 PM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 789<https://urldefense.com/v3/__http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/789__;!!Nmw4Hv0!0T7ZRR4ZY-EJCNVcYuzEb-7IyAraMGbQ7buWHTuOYJQJmqxoSdBw094fANmgNUPW5C1tBibNR8Ol7qPuKYyBqGg_0mx2-ps$>.

**Pull request merged**
