### PR TITLE
added kernels of Voigt parameters

### PR DESCRIPTION
**Pull request by herurisa**
Updates parameter file, read external Voigt model and compute
kernels based on Voigt parameters.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 359](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/359). Fix your mistakes and push your changes back to your branch herurisa/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 360](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/360). Fix your mistakes and push your changes back to your branch herurisa/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 361](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/361).

**Comment by komatits** [comment]
accept

On 12/14/2015 09:20 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 361
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/361>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/506#issuecomment-164548156>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
