### PR TITLE
updates SOURCE and Par_file structures; fixes MPI issue with moving sources on GPU; adds Dirichlet condition on acoustic PML on GPU

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 760](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/760).

**Comment by bottero** [comment]
Nice! Thank you

**Comment by danielpeter** [comment]
accept

**Pull request merged**
