### PR TITLE
New, more effective, way of dealing with moving sources in GPU

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 746](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/746). Please fix the problems and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 747](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/747). Please fix the problems and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 748](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/748).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
