### PR TITLE
source cleaning

### PR DESCRIPTION
**Pull request by danielpeter**
updates read/write for databases; 
cleans initialization and read setup; 
moves local parameters out of module definition; 
updates gpu/cpu interaction

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 347](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/347). Fix your mistakes and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 348](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/348). Fix your mistakes and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 349](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/349).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
