### PR TITLE
Adding MPI support for external model

### PR DESCRIPTION
**Pull request by EtienneBachmann**
-Added SAVE_MODEL flag in Par_file to enable specfem to output a model in different types ( legacy, binary, ascii)\
-Added MPI support to read an external model

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 257](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/257). Fix your mistakes and push your changes back to your branch EtienneBachmann/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 258](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/258).

**Comment by komatits** [comment]
accept

On 09/09/2015 11:40 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 258
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/258>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/396#issuecomment-139053729>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKdBk7RntDCGJxCiYIHKHnaZr8u_6ks5owJ61gaJpZM4F6k9G.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
