### PR TITLE
Fix some bugs with acoustic forcing option and add moving sources capabilities

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 406](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/406). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 407](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/407). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 408](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/408).

**Comment by komatits** [comment]
accept

On 24/05/2016 11:47, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 408
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/408>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/576#issuecomment-221219766>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
