### PR TITLE
updates travis; fixes poroelastic Stacey for kernel simulations; adds poroelastic kernel reference example

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 790](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/790).

**Comment by danielpeter** [comment]
accept

**Comment by danielpeter** [comment]
accept

On 22 Sep 2022, at 10:40 AM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 790<https://urldefense.com/v3/__http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/790__;!!Nmw4Hv0!3DcHkeX_KJAsyX58TBaPQ46w3heRps6WGBBeWAjo73iGZ_lKXcpveiko9YVkpoRhksT5aWNl9-ChEIMhKEw9hqFS77q1hn0$>.

**Pull request merged**
