### PR TITLE
finish the first version of undo_attenuation

### PR DESCRIPTION
**Pull request by xiezhinan**
Since I have problem during install hub, thus I have a  "Merge branch 'devel' of  ...".
I am deeply sorry for that, I will fix that soon.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 168](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/168). Fix your mistakes and push your changes back to your branch xiezhinan/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 169](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/169). Fix your mistakes and push your changes back to your branch xiezhinan/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 170](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/170).

**Comment by komatits** [comment]
accept

On 04/03/2015 07:24 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 170
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/170>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/280#issuecomment-89165773>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
