### PR TITLE
fixed minor regression

### PR DESCRIPTION
**Pull request by rmodrak**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by rmodrak** [comment]
Elliot pointed out a makefile mistake a long time ago.  After missing his comment initially, now finally I corrected it.

**Comment by rmodrak** [comment]
Thanks Elliot, for pointing out the mistake earlier.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 245](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/245).

**Comment by komatits** [comment]
accept

On 06/13/2015 06:30 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 245
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/245>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/377#issuecomment-111668578>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
