### PR TITLE
small updates and code formatting; changes variable names in constants.h.in

### PR DESCRIPTION
**Pull request by danielpeter**
needs re-configuration to work

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 339](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/339). Fix your mistakes and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by danielpeter** [comment]
fails due to an internal error of the intel fortran compiler...

**Comment by luet** [comment]
I have rerun the test and the error went away: build 340
<http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/340>
.
I am not sure what that error is about. We are running Intel 14.0 I will
update to 16.0 next week.

On Fri, Nov 20, 2015 at 5:54 AM, daniel peter <notifications@github.com>
wrote:

> fails due to an internal error of the intel fortran compiler...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/487#issuecomment-158357855>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Pull request closed without merging**
