### PR TITLE
Fix some bugs and add a lot of small enhancements

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
src/shared/lagrange_poly.f90
This Pull Request will be closed. Please fix your commit and open a new Pull Request.

Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" src/shared/lagrange_poly.f90
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT src/shared/lagrange_poly.f90-o src/shared/lagrange_poly.f90
Although you should be aware that some characters won't be converted properly.

**Comment by komatits** [comment]
Accepting it manually; it is just a matter of running the code beautifier to get rid of all accented letters automatically.

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
src/shared/lagrange_poly.f90
This Pull Request will be closed. Please fix your commit and open a new Pull Request.

Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" src/shared/lagrange_poly.f90
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT src/shared/lagrange_poly.f90-o src/shared/lagrange_poly.f90
Although you should be aware that some characters won't be converted properly.

**Comment by buildbot-princeton** [comment]
The following files in your commit contain non-ASCII characters:
src/shared/lagrange_poly.f90
This Pull Request will be closed. Please fix your commit and open a new Pull Request.

Under Linux, one way to check for non-ASCII characters is:
grep --color='auto' -P -n "[\x80-\xFF]" src/shared/lagrange_poly.f90
This will give you the line number, and will highlight non-ASCII chars in red.

To convert the non-ASCII characters automatically, under Linux, you can use:
iconv -f utf-8 -t ASCII//TRANSLIT src/shared/lagrange_poly.f90-o src/shared/lagrange_poly.f90
Although you should be aware that some characters won't be converted properly.

**Pull request merged**
