### PR TITLE
changed the default for GNU gfortran from -O2 to -O3

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 231](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/231).

**Comment by komatits** [comment]
accept

On 05/21/2015 06:09 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 231
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/231>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/356#issuecomment-104335278>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKTXdJW6cnAbIqGD_EX6TsDR7WKVUks5oLfqrgaJpZM4EjnJh.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
accept

On 05/21/2015 06:10 PM, buildbot-princeton wrote:
> Merged #356 <https://github.com/geodynamics/specfem2d/pull/356>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/356#event-310829973>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKfaph2zyZ8c6GKtqp2sBTxGycZm_ks5oLfrqgaJpZM4EjnJh.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
