### PR TITLE
Moving acoustic source capabilities in GPU (forward and adjoint)

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 737](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/737). Please fix the problems and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 738](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/738). Please fix the problems and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 739](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/739). Please fix the problems and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 740](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/740). Please fix the problems and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 741](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/741). Please fix the problems and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 742](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/742).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
