### PR TITLE
Fix some typo and add a new functionnality (integrated_energy_field)

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 382](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/382). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 383](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/383). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 384](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/384). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 385](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/385).

**Comment by komatits** [comment]
accept

On 17/03/2016 12:43, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 385
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/385>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/546#issuecomment-197841837>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
