### PR TITLE
Ajustments to allow for viscoacoustic axisymmetric simulations

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
There was an error running buildbot. The system administrator needs to look into it

**Comment by bottero** [comment]
Kesako? :s
Première fois que Buildbot me raconte ça.

A+

Alexis Bottero, PhD student
Tel: +0033 6 95 17 00 97
Waves and imaging
Laboratoire de Mécanique et d'Acoustique de Marseille

2018-01-11 15:37 GMT+01:00 buildbot-princeton <notifications@github.com>:

**Comment by komatits** [comment]
It was Github.com that was down for a while, and thus Buildbot failed because it could not connect to github.com. Thus accepting the pull request manually, now that the site is back.

**Pull request merged**
