### PR TITLE
fixed bug in diagonal Hessian illumination expression

### PR DESCRIPTION
**Pull request by rmodrak**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by komatits** [comment]
It seems BuildBot is down, thus accepting the request manually.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 307](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/307).

**Comment by luet** [comment]
The buildbot is fixed now. I ran the tests and the commits were
successful: build
311
<http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/311>
 and nightly 135
<http://specfem2d-buildbot.princeton.edu/builders/specfem2d_nightly/builds/135>
.
David

On Mon, Oct 26, 2015 at 9:16 AM, buildbot-princeton <
notifications@github.com> wrote:

> Your changes passed the buildbot test. See build 307
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/307>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/456#issuecomment-151130114>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by komatits** [comment]
accept

On 10/26/2015 02:16 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 307
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/307>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/456#issuecomment-151130114>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKa0EvEilyjYDUndCdQ_A3-sam-k_ks5o_h9IgaJpZM4GVRBj.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
