### PR TITLE
 Added GPU support for PMLs in acoustic case

### PR DESCRIPTION
**Pull request by EtienneBachmann**
Also, corrected a bug for Stacey boundary conditions on GPU.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 732](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/732). Please fix the problems and push your changes back to your branch EtienneBachmann/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 733](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/733).

**Comment by danielpeter** [comment]
accept

**Pull request merged**
