### PR TITLE
fixed a bug in the axial conditions for gradients in the fluid

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 217](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/217). Fix your mistakes and push your changes back to your branch komatits/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 218](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/218).

**Comment by komatits** [comment]
accept

On 05/08/2015 03:16 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 218
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/218>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/338#issuecomment-100059757>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
