### PR TITLE
Fix a problem with pmls in cubit2specfem2d.py

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 124](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/124).

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Comment by komatits** [comment]
accept

On 03/04/2015 02:53 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 124
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/124>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/226#issuecomment-77160830>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request closed without merging**
