### PR TITLE
Non-recursive make

### PR DESCRIPTION
**Pull request by QuLogic**
Port the non-recursive build system from specfem3d. Also, switch to the `autoconf_cig` submodule instead of holding an old copy of the files around. There were several typos I found while making this change, so there's a chance that some typos still exist. It seems to work in `gfortran` and `ifort`, though.

@luet: You should be able to enable parallel make with this PR.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 95](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/95).

**Comment by komatits** [comment]
accept

On 01/07/2015 06:29 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 95
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/95>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/176#issuecomment-68980661>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Thanks! Very useful.

On 01/07/2015 06:28 AM, Elliott Sales de Andrade wrote:
> Port the non-recursive build system from specfem3d. Also, switch to the
> |autoconf_cig| submodule instead of holding an old copy of the files
> around. There were several typos I found while making this change, so
> there's a chance that some typos still exist. It seems to work in
> |gfortran| and |ifort|, though.
>
> @luet <https://github.com/luet>: You should be able to enable parallel
> make with this PR.
>
> ------------------------------------------------------------------------
>
>
>         You can merge this Pull Request by running
>
>    git pull https://github.com/QuLogic/specfem2d non-recursive-make
>
> Or view, comment on, or merge it at:
>
> https://github.com/geodynamics/specfem2d/pull/176
>
>
>         Commit Summary
>
>   * BLD: Move extra programs into auxiliaries directory.
>   * BLD: Move force_ftz.c to specfem2d directory.
>   * BLD: Switch m4 to submodule.
>   * Add underscores to some file names.
>   * BLD: Modify scotch to build the same as specfem3D.
>   * BLD: Port non-recursive make from 3D code.
>   * BLD: Get out-of-source builds working here.
>   * Fix bug in MPI mode.
>
>
>         File Changes
>
>   * *M* .gitignore
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-0> (4)
>   * *M* .gitmodules
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-1> (3)
>   * *M* Makefile.in
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-2> (178)
>   * *M* configure
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-3> (683)
>   * *M* configure.ac
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-4> (60)
>   * *A* m4
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-5> (1)
>   * *D* m4/ac_pkg_swig.m4
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-6> (126)
>   * *D* m4/cit_fortran.m4
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-7> (363)
>   * *D* m4/cit_funcstring.m4
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-8> (47)
>   * *D* m4/cit_hdf.m4
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-9> (81)
>   * *D* m4/cit_mpi.m4
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-10> (489)
>   * *D* m4/cit_numpy.m4
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-11> (33)
>   * *D* m4/cit_petsc.m4
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-12> (383)
>   * *D* m4/cit_python.m4
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-13> (465)
>   * *M* setup/config.h.in
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-14> (7)
>   * *A* src/auxiliaries/Makefile
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-15> (64)
>   * *R* src/auxiliaries/adj_seismogram.f90
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-16> (0)
>   * *R* src/auxiliaries/check_quality_external_mesh.f90
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-17> (0)
>   * *R* src/auxiliaries/convolve_source_timefunction.f90
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-18> (0)
>   * *A* src/auxiliaries/rules.mk
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-19> (148)
>   * *A* src/meshfem2D/Makefile
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-20> (64)
>   * *D* src/meshfem2D/Makefile.in
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-21> (220)
>   * *A* src/meshfem2D/rules.mk
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-22> (131)
>   * *M* src/meshfem2D/scotch_5.1.12b/src/Makefile
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-23> (28)
>   * *M* src/meshfem2D/scotch_5.1.12b/src/Makefile.inc.in
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-24> (4)
>   * *M* src/meshfem2D/scotch_5.1.12b/src/scotch/Makefile
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-25> (1)
>   * *A* src/shared/Makefile
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-26> (64)
>   * *R* src/shared/define_shape_functions.f90
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-27> (0)
>   * *A* src/shared/rules.mk
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-28> (85)
>   * *A* src/specfem2D/Makefile
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-29> (64)
>   * *D* src/specfem2D/Makefile.in
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-30> (682)
>   * *R* src/specfem2D/check_grid.F90
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-31> (0)
>   * *R* src/specfem2D/force_ftz.c
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-32> (0)
>   * *R* src/specfem2D/plot_gll.f90
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-33> (0)
>   * *R* src/specfem2D/plot_post.F90
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-34> (0)
>   * *M* src/specfem2D/pml_init.F90
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-35> (2)
>   * *R* src/specfem2D/prepare_initial_field.F90
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-36> (0)
>   * *A* src/specfem2D/rules.mk
>     <https://github.com/geodynamics/specfem2d/pull/176/files#diff-37> (292)
>
>
>         Patch Links:
>
>   * https://github.com/geodynamics/specfem2d/pull/176.patch
>   * https://github.com/geodynamics/specfem2d/pull/176.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/176>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
