### PR TITLE
remove module only in subprograms

### PR DESCRIPTION
**Pull request by EtienneBachmann**
I removed some "use module, only" by "use module" in second order subprograms. This will avoid drawer effects modifying these subprograms.
I also removed loop variables (i,j,ispec...) from the module and declared them locally, to also avoid possible future mistakes.
I added some flags "-Wunused -Werror " in the configure file.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 115](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/115). Fix your mistakes and push your changes back to your branch EtienneBachmann/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by EtienneBachmann** [comment]
I removed some "use module, only" by "use module" in second order subprograms. This will avoid drawer effects modifying these subprograms. 
I also removed loop variables (i,j,ispec...) from the module and declared them locally, to also avoid possible future mistakes.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 116](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/116).

**Comment by komatits** [comment]
accept

On 02/12/2015 03:31 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 116
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/116>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/213#issuecomment-74079409>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
