### PR TITLE
changed flag add_Bielak_conditions to four flags: add_Bielak_conditions_bottom, add_Bielak_conditions_right, add_Bielak_conditions_top and add_Bielak_conditions_left

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by komatits** [comment]
Never got any answer from BuildBot (as yesterday), thus accepting the request manually. It seems BuildBot is partly down, thus let me cc David @luet

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 378](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/378).

**Comment by komatits** [comment]
accept

On 26/02/2016 19:40, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 378
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/378>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/539#issuecomment-189418348>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
@komatits You already merged that PR manually so don't expect that buildbot will merge it again.

**Pull request merged**
