### PR TITLE
Add a new functionnality to cubit2specfem2d.py (several acoustic or elastic

### PR DESCRIPTION
**Pull request by bottero**
pmls)

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 377](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/377).

**Comment by komatits** [comment]
accept

On 19/02/2016 19:30, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 377
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/377>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/537#issuecomment-186352216>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Great! Very useful.

Could also be worth merging it with Ting Yu's version for QUAD9 at some 
point, to maintain a single version. (currently we have two)

Best,
Dimitri.

On 19/02/2016 19:20, Bottero wrote:
> pmls)
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/geodynamics/specfem2d/pull/537
>
>
>         Commit Summary
>
>   * Add a new functionnality to cubit2specfem2d.py (several acoustic or
>     elastic pmls)
>
>
>         File Changes
>
>   * *M* utils/cubit2specfem2d/cubit2specfem2d.py
>     <https://github.com/geodynamics/specfem2d/pull/537/files#diff-0> (121)
>
>
>         Patch Links:
>
>   * https://github.com/geodynamics/specfem2d/pull/537.patch
>   * https://github.com/geodynamics/specfem2d/pull/537.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/537>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
