### PR TITLE
Implement an option to read an external velocity model (as in SPECFEM3D)

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 136](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/136). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 137](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/137). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by komatits** [comment]
Committed by me, thus closing this one.

**Pull request closed without merging**
