### PR TITLE
Fix some bugs with AXISYM option

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 202](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/202). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 203](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/203). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 204](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/204).

**Comment by komatits** [comment]
accept

On 05/04/2015 04:34 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 204
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/204>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/323#issuecomment-98729156>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
