### PR TITLE
done fixing the new version of attenuation; also switched from the far less classical reference of reading relaxed velocities from the Par_file to the very classical convention of reading unrelaxed values instead

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 302](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/302). Fix your mistakes and push your changes back to your branch komatits/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 303](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/303).

**Comment by komatits** [comment]
accept

On 10/20/2015 06:29 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 303
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/303>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/444#issuecomment-149623733>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
