### PR TITLE
clean further the code for visco-kernel computation

### PR DESCRIPTION
**Pull request by xiezhinan**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 160](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/160).

**Comment by komatits** [comment]
accept

On 03/30/2015 04:20 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 160
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/160>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/270#issuecomment-87698115>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by EtienneBachmann** [comment]
This commit introduced the saving of Stacey boundary conditions twice, when save_forward is true. I guess Zhinan thought that this save was accidentally suppressed, but in fact, in a former commit, I moved this saving part outisde the time loop (in finalize_simulation), in order to make it consistent with the GPU version, and to reduce the I/O.  I will remove the wrong parts in a future commit.

**Pull request merged**
