### PR TITLE
Adding CUDA support part 1 : Configuration for CUDA mode, calls to (currently) dummy CUDA functions. Please do not attemp t to turn on the GPU_MODE until next commit

### PR DESCRIPTION
**Pull request by EtienneBachmann**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 100](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/100). Fix your mistakes and push your changes back to your branch EtienneBachmann/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 101](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/101).

**Comment by komatits** [comment]
accept

On 01/14/2015 08:49 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 101
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/101>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/182#issuecomment-69979111>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
