### PR TITLE
Add possibility to record several signal types. e.g seismotype = 1,3,4

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 723](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/723). Please fix the problems and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
It does look like there is an issue with the LuoYang_fluid_solid_kernel case. The image created are wrong:
http://seismobot.princeton.edu/nightly_build_pdf/specfem2d/LuoYang_fluid_solid_kernel/
I have tried running by hand, and I get the same results. Can someone try on their side?

**Comment by danielpeter** [comment]
hi David,

thanks for looking into it! the PR #1021 should fix this issue. still some more work to do to fix the travis tests...

best,
daniel

**Pull request merged**
