### PR TITLE
Add constants OUTPUT_FILES and IN_DATA_FILES in 2D code to follow 3D...

### PR DESCRIPTION
**Pull request by bottero**
…version. Contains also many developments necessary to option NUMBER_OF_SIMULTANEOUS_RUNS. To be continued...

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 539](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/539). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 540](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/540). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 541](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/541). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by komatits** [comment]
Accepting manually, will fix the dependency problem in rules.mk later

**Comment by komatits** [comment]
Dependencies fixed.

**Pull request merged**
