### PR TITLE
implemented --enable-debug for "configure", as in the 3D codes

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 182](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/182). Fix your mistakes and push your changes back to your branch komatits/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 183](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/183).

**Comment by komatits** [comment]
accept

On 04/24/2015 02:25 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 183
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/183>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/303#issuecomment-95761783>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
