### PR TITLE
put USE_NEW_SOLVOPT_ROUTINE back to .true. by default

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 286](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/286). Fix your mistakes and push your changes back to your branch komatits/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by komatits** [comment]
BuildBot error apparently, thus let me accept the pull request manually

On 10/04/2015 03:12 PM, buildbot-princeton wrote:
> Your changes failed the buildbot test. See build 286
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/286>.
> Fix your mistakes and push your changes back to your branch
> komatits/specfem2d:devel. This pull-request will be reopened
> automatically. You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/427#issuecomment-145349345>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
I am not sure this was a mistake. I wonder if this is a problem that we only run into randomly when doing parallel make. But it does compile now.

    src/specfem2D/define_external_model.f90(48): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [SPECFEM_PAR]
      use specfem_par, only: poroelastcoef,density,kmato
    ------^
    src/specfem2D/define_external_model.f90(134): error #6406: Conflicting attributes or multiple declaration of name.   [DENSITY]
        density(1,kmato(ispec)) = rho(i,j,ispec)
    --------^
    src/specfem2D/define_external_model.f90(135): error #6406: Conflicting attributes or multiple declaration of name.   [POROELASTCOEF]
            poroelastcoef(3,1,kmato(ispec)) = rho(i,j,ispec) * vp(i,j,ispec) * vp(i,j,ispec)
    --------^
    src/specfem2D/define_external_model.f90(136): error #6406: Conflicting attributes or multiple declaration of name.   [POROELASTCOEF]
            poroelastcoef(2,1,kmato(ispec)) =  rho(i,j,ispec) * vs(i,j,ispec) * vs(i,j,ispec)
    --------^
    src/specfem2D/define_external_model.f90(48): error #6580: Name in only-list does not exist.   [POROELASTCOEF]
      use specfem_par, only: poroelastcoef,density,kmato
     -------------------------^
    src/specfem2D/define_external_model.f90(48): error #6580: Name in only-list does not exist.   [DENSITY]
     use specfem_par, only: poroelastcoef,density,kmato 
    ---------------------------------------^
    src/specfem2D/define_external_model.f90(48): error #6580: Name in only-list does not exist.   [KMATO]
      use specfem_par, only: poroelastcoef,density,kmato
    -----------------------------------------------^

**Comment by QuLogic** [comment]
There's a typo in the dependency rule; I will open a PR.

**Comment by luet** [comment]
Thanks @QuLogic

**Pull request merged**
