### PR TITLE
A lot of small changes while trying to locate a bug...

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 242](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/242). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 243](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/243).

**Comment by komatits** [comment]
accept

On 06/03/2015 03:44 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 243
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/243>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/368#issuecomment-108422584>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKaM75qvfnh_GyKsbgLdq-Vv7Hogfks5oPvxWgaJpZM4E2aRE.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
