### PR TITLE
new version of subroutine shift_velocities_from_f0() by Emmanuel Chaljub (to take into account the 1/N factor, among other things)

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by komatits** [comment]
It seems BuildBot had a problem, thus accepting it manually.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 307](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/307).

**Comment by komatits** [comment]
accept

On 10/26/2015 02:16 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 307
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/307>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/455#issuecomment-151130115>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
