### PR TITLE
added SAVE_DIAGONAL_HESSIAN parameter to constants.h

### PR DESCRIPTION
**Pull request by rmodrak**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 312](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/312). Fix your mistakes and push your changes back to your branch rmodrak/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 313](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/313). Fix your mistakes and push your changes back to your branch rmodrak/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 314](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/314).

**Comment by rmodrak** [comment]
Added SAVE_DIAGONAL_HESSIAN parameter to setup/constants.h.  Besides modifying setup/constants.h, also had to modify src/specfem2d/save_adjoint_kernels.f90.  Two different diagonal approximations to the Hessian are written out to the files proc??????_hessian1_kernel.bin and proc??????_hessian2_kernel.bin, respectively.  After consulting with Etienne, a short-lived legacy format option has been removed from  src/specfem2d/save_adjoint_kernels.f90.

**Comment by komatits** [comment]
accept

On 10/26/2015 09:35 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 314
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/314>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/457#issuecomment-151276572>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKU3-pNAg6FfOQvn9BhxB9BFk9R_Dks5o_oX6gaJpZM4GV9Rq.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
