### PR TITLE
fixed a warning in EXAMPLES/global_Earth_ak135f/create_mesh_AK135F_2D_with_central_cube_no_PML.F90

### PR DESCRIPTION
**Pull request by komatits**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 206](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/206).

**Comment by komatits** [comment]
accept

On 05/07/2015 12:29 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 206
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/206>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/326#issuecomment-99630089>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by QuLogic** [comment]
Aren't `integer`s 4 bytes while `double precision` is 8, thus only sorting half the array?

**Comment by komatits** [comment]
Yes, but the equivalence statement I added is just to avoid wasting 
memory, i.e. it works even with arrays of different size and the result 
is correct.

On 05/07/2015 03:01 AM, Elliott Sales de Andrade wrote:
> Aren't |integer|s 4 bytes while |double precision| is 8, thus only
> sorting half the array?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/326#issuecomment-99664302>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
