### PR TITLE
Add an example (with PMLs layers) to cubit2specfem2d

### PR DESCRIPTION
**Pull request by bottero**
Add an example (with PMLs layers) to cubit2specfem2d

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 108](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/108). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
It's my problem: "No space left on device". Let me take care of it.

On Fri, Feb 6, 2015 at 9:23 AM, buildbot-princeton <notifications@github.com
> wrote:

> Your changes failed the buildbot test. See build 108
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/108>.
> Fix your mistakes and push your changes back to your branch
> bottero/specfem2d:devel. This pull-request will be reopened automatically.
> You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/203#issuecomment-73243197>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 109](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/109).

**Comment by luet** [comment]
accept

On Fri, Feb 6, 2015 at 9:44 AM, buildbot-princeton <notifications@github.com
> wrote:

> Your changes passed the buildbot test. See build 109
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/109>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/203#issuecomment-73246337>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Pull request closed without merging**
