### PR TITLE
Various updates for the smoothing routine

### PR DESCRIPTION
**Pull request by EtienneBachmann**
Modifications in the smoothing routine : 
-The integral convolution is not approximated anymore : we use a surface integral following the quadrature rule for spectral elements.
-CPU code optimized.
-Added CUDA support, a new flag (GPU_MODE) must be provided to the routine.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 315](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/315). Fix your mistakes and push your changes back to your branch EtienneBachmann/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 316](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/316).

**Comment by komatits** [comment]
accept

On 10/27/2015 10:53 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 316
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/316>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/458#issuecomment-151656619>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
