### PR TITLE
Add capabilities for enforcing displacement somewhere plus some small other changes

### PR DESCRIPTION
**Pull request by bottero**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 412](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/412). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 413](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/413). Fix your mistakes and push your changes back to your branch bottero/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 414](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/414).

**Comment by komatits** [comment]
accept

On 31/05/2016 19:54, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 414
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/414>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/579#issuecomment-222767723>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFjDKTA6aVf7p1S5B5RBIuiP7n8OhbJbks5qHHXQgaJpZM4IquJb>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
