### PR TITLE
source cleanup and renaming variables to make it similar to 3D versions

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 336](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/336). Fix your mistakes and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by danielpeter** [comment]
the builbot test fails because of a missing cleanup before compilation. it checks the serial compilation for postprocess executables after parallel compilation of default targets without cleaning out older object files -> linker complains about missing mpi functions... 

this is a bug to fix in the buildbot script which can not be done by another commit here...

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 337](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/337). Fix your mistakes and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes failed the buildbot test. See [build 338](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/338). Fix your mistakes and push your changes back to your branch danielpeter/specfem2d:devel. This pull-request will be reopened automatically.         You don't need to create a new pull request

**Comment by luet** [comment]
Is this one an actual problem?

On Thu, Nov 19, 2015 at 10:38 AM, buildbot-princeton <
notifications@github.com> wrote:

> Your changes failed the buildbot test. See build 338
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/338>.
> Fix your mistakes and push your changes back to your branch
> danielpeter/specfem2d:devel. This pull-request will be reopened
> automatically. You don't need to create a new pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/486#issuecomment-158092461>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Pull request closed without merging**
