### PR TITLE
Split the code update_displacement_scheme.f90

### PR DESCRIPTION
**Pull request by xiezhinan**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by luet** [comment]
I am not sure why it's running again. Let's just let it go through (it's a
5 min process).


On Wed, Mar 25, 2015 at 10:04 AM, buildbot-princeton <
notifications@github.com> wrote:

> The files changed require a buildbot test. Buildbot has started.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/262#issuecomment-86042534>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by luet** [comment]
All right something is not right. Let me look at it. I was working on the
code. I thought I was safe but maybe I wasn't.

On Wed, Mar 25, 2015 at 10:09 AM, buildbot-princeton <
notifications@github.com> wrote:

> The files changed require a buildbot test. Buildbot has started.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/262#issuecomment-86044373>.
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 150](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/150).

**Comment by xiezhinan** [comment]
Hi David,

I think you are safe.
The problem may caused that I have pushed three times.
Since I have tested several examples to make sure my commit is fine.
After fixed problems one by one , I pushed four times.

That is a stupid way to make sure the change do not lost and make sure those changes are fine.
I will change that way to avoid troubles for you.

Thank you so much, David.
Best regards,
Zhina

**Comment by luet** [comment]
Yes this is definitely not the way to do it. I am not sure what you did exaclty but from the GitHub point of view you kept creating pull-requests. You should only open a pull-request once. If you realize you made a mistake, close the initial one and open a new one.

This pull-request passed the buildbot tests see [build 153](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/153).
I'll let someone else accept it.

**Comment by komatits** [comment]
accept

On 03/25/2015 04:37 PM, David Luet wrote:
> Yes this is definitely not the way to do it. I am not sure what you did
> exaclty but from the GitHub point of view you kept creating
> pull-requests. You should only open a pull-request once. If you realize
> you made a mistake, close the initial one and open a new one.
>
> This pull-request passed the buildbot tests see build 153
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/153>.
> I'll let someone else accept it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/262#issuecomment-86085482>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by komatits** [comment]
accept

On 03/25/2015 03:11 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 150
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/150>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/262#issuecomment-86044838>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 154](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/154).

**Comment by komatits** [comment]
accept

On 03/25/2015 04:58 PM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 154
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/154>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/262#issuecomment-86094607>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by xiezhinan** [comment]
Hi David and Dimitri,

Thank you so much, David. 
I will follow you way in future commit.

By the way, could you please let the buildbot also test fully the adjoint example.
I found that I can not get the same result as the old version of the code, such as  theLuoYang_fluid_solid_kernel.

Currently, the buildbot only test the first stage, that is the forward simulation, in the adjoint example.

Thanks again,
Best regards,
Zhinan

**Comment by QuLogic** [comment]
@xiezhinan If you want to save your in-progress work on GitHub, then you should try creating some temporary branches instead. PRs revolve around temporary branches; if you push to the one related to a PR (such as `devel` here), then the PR is updated. But if instead you push to a _different_ branch, it will not affect the PRs you already have open.

Unlike SVN, branches in git are cheap; there's no real penalty to using them.

Of course, related to that, as @luet pointed out, you do not need to open a PR immediately. You can make a few commits before opening one.

**Comment by komatits** [comment]
Hi Zhinan, Hi all,

I think that is an excellent suggestion (to all: this comes from the 
fact that the 2D code was broken for a week or so in spite of all the 
tests BuildBot does because we check forward runs but do not check any 
adjoint / kernel run).

Thus, what about adding EXAMPLES/LuoYang_fluid_solid_kernel to BuildBot 
nightly builds for SPECFEM2D? (and ideally something similar for the 3D 
code as well)

However this means defining a way of knowing if a kernel is wrong i.e. 
if it has changed (apart from roundoff noise) compared to a precomputed 
reference kernel. Any idea about how to do that accurately and reliably?

I think that is an important issue (the code was broken for a week or 
so, and we did not know; Zhinan discovered that because for another 
project he ran the LuoYang_fluid_solid_kernel example; otherwise it 
could have been weeks or months).

Thanks,
Dimitri.

On 03/26/2015 01:49 AM, Xie Zhinan wrote:
> Hi David and Dimitri,
>
> Thank you so much, David.
> I will follow you way in future commit.
>
> By the way, could you please let the buildbot also test fully the
> adjoint example.
> I found that I can not get the same result as the old version of the
> code, such as theLuoYang_fluid_solid_kernel.
>
> Currently, the buildbot only test the first stage, that is the forward
> simulation, in the adjoint example.
>
> Thanks again,
> Best regards,
> Zhinan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/262#issuecomment-86267440>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
