### PR TITLE
make the "LuoYang_fluid_solid_kernel" example run with Stacey

### PR DESCRIPTION
**Pull request by xiezhinan**
make the "LuoYang_fluid_solid_kernel" example run with Stacey.
Changes have been also made to the file adj_source.f90, since it is inconsistent with the current convention in naming the Station.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by xiezhinan** [comment]
Hi all, I notice that the imagetype_JPEG = 1 does not work for the  fluid solid simulation.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 93](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/93).

**Comment by xiezhinan** [comment]
Hi all, soory,  I noticed that the imagetype_JPEG = 10 does not work for the fluid solid simulation, not  imagetype_JPEG = 1

**Comment by komatits** [comment]
accept

On 01/01/2015 06:30 AM, buildbot-princeton wrote:
> Your changes passed the buildbot test. See build 93
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/93>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/pull/172#issuecomment-68480707>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Pull request merged**
